FROM node:16 AS build
ARG VITE_APP_SERVER_URL
WORKDIR /usr/src/app
COPY package.json package-lock.json tsconfig.base.json nx.json ./
COPY apps/client apps/client/
RUN npm install
RUN npx nx build apps-client

FROM pierrezemb/gostatic
COPY --from=build /usr/src/app/dist/apps/client /srv/http/
CMD ["-port","8080","-https-promote", "-enable-logging", "-fallback", "index.html"]
